version: "3.8"
services:
  db:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $PG_ROOT_PASSWORD
    ports:
      - "5434:5432"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - $LOCAL_PORT:$PORT
volumes:
  postgres-data:
    driver: local
